#!/bin/sh

sep=:

# If everything including com is in SpiralApplet.jar,
# then can run it standalone with no classpath
#exec java -jar SpiralApplet.jar "$@"

# Have to do it this way if com is not in SpiralApplet.jar
#exec java -classpath "SpiralApplet.jar${sep}donhatchsw.jar" SpiralApplet "$@"

# This way doesn't require jar to be made at all, just the class files
#exec java -classpath ".${sep}c:/Program Files/Java/jdk1.7.0_21/jre/lib/jfxrt.jar${sep}donhatchsw.jar" SpiralApplet "$@"
exec java -classpath ".${sep}donhatchsw.jar" SpiralApplet "$@"

# Requires neither jar nor donhatchsw to be made (note that we still *compile* out of donhatchsw.jar in current directory though... this is just useful for non-interface fixes or debugging in donhatchsw)
#exec java1.7 -Dcom.sun.scenario.animation.vsync=true  -Dcom.sun.scenario.animation.pulse=500 -classpath ".${sep}c:/Program Files/Java/jdk1.7.0_21/jre/lib/jfxrt.jar${sep}donhatchsw/myGitRepo" SpiralApplet "$@"
